# Server Config
server:
  port: 8080
  servlet:
    session:
      timeout: 30m
    context-path: /
  address: 0.0.0.0

# Database config
spring:
  # Oracle Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/exdb
    username: exuser
    password: ex@2024
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: HikariPoolBooks
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    format:
      date: dd/MM/yyyy
      date-time: dd/MM/yyyy HH:mm
      time: HH:mm
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ex_sch
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    #    defer-datasource-initialization: true
    open-in-view: false
  # Flyway configurations
  flyway:
    locations: classpath:db/migration
    enabled: false
    validate-on-migrate: false



#JWT Security Key
#jwt_secret: cl$ksc^nas%lkdm!cz@xclk#as&dmka;s28*392da%jskd#n9827@3498%

project:
  image: images/


logging:
  level:
    org:
      hibernate: error
      hibernate.SQL: error
      springframework: error
      springframework.security: debug

springdoc:
  swagger-ui:
    defaultModelsExpandDepth: -1
    doc-expansion: false
    operationsSorter: alpha
    tagsSorter: alpha




oci:
  objectstorage:
    namespace:
    bucketName:
    tenancyId:
    userId:
    fingerprint:
    pemFilePath:

#  region: uk-london-1
#  tenancy: ocid1.tenancy.oc1..aaaaaaaat5gpz247yn6fhp7xw23yt4ghnymubvdqkc3jchtcsqmaeanqvgwq
#  user: ocid1.user.oc1..aaaaaaaakoq4g2bpsqujft4h5cjwkaks6dw47stzy5hr4ywfbislheomqusa
#  fingerprint: 3d:b7:d6:40:e9:d1:54:a5:a4:2f:03:04:f0:68:cc:f8
#  privateKeyPath: classpath:private-key.pem
#  bucketName: Attachment_Project
#  namespace: lrsck9fucaye

attachmentFiles:
  path: C:\ex

bank:
  excel:
    path: src/main/resources/excel/banks.xlsx
bankBranches:
  excel:
    path: src/main/resources/excel/bankBranches.xlsx



