ALTER TABLE gl_voucher_details
    MODIFY row_notes NULL;


CREATE TABLE app_attached_file_types
(
    type_id   NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_desc VARCHAR2(50),
    CONSTRAINT pk_app_attached_file_types PRIMARY KEY (type_id)
);

CREATE TABLE app_attached_files
(
    file_id      NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    related_id   NUMBER(38, 0),
    file_name    VARCHAR2(100),
    content_type VARCHAR2(30),
    file_content BLOB,
    file_type_id NUMBER(38, 0),
    CONSTRAINT pk_app_attached_files PRIMARY KEY (file_id)
);

ALTER TABLE app_attached_files
    ADD CONSTRAINT FK_APP_ATTACHED_FILES_ON_FILE_TYPE FOREIGN KEY (file_type_id) REFERENCES app_attached_file_types (type_id);

ALTER TABLE gl_voucher_master
    ADD related_file_id NUMBER(38, 0);

ALTER TABLE gl_voucher_master
    ADD CONSTRAINT uc_gl_voucher_master_related_file UNIQUE (related_file_id);

INSERT INTO app_attached_file_types VALUES(1,'سندات قيد');
INSERT INTO app_attached_file_types VALUES(2,'سندات صرف');
INSERT INTO app_attached_file_types VALUES(3,'سندات قبض');